# azure-pipelines.yml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python --version
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd main
    python -m pytest
  displayName: 'Run tests'

- script: |
    cd main
    python main.py
  displayName: 'Start the application'
